version: '3.4'

services:
  db:
    image: mysqlUdemy:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "dbdata:/var/lib/mysql"
    restart: always
    build:
      context: ./AspNetCoreWithDocker
      dockerfile: Dockerfile    
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_core_docker
    ports:
      - "3308:3306"
    networks:
      - udemy-network

  restwithaspnetudemy:
    image: restcoredockerapi:latest
    build:
      context: ./AspNetCoreWithDocker
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:50977"
      - "4000:44383"
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network

networks: 
  udemy-network:
    driver: bridge

volumes:
  dbdata: {}