CREATE TABLE IF NOT EXISTS books (
	Id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Author VARCHAR(50) NOT NULL,
	LaunchDate DATETIME(6) NOT NULL,
	Price DECIMAL(65,2) NOT NULL,
	Titel VARCHAR(10) NOT NULL 
) ENGINE = INNODB DEFAULT CHARSET=latin1;
