CREATE TABLE IF NOT EXISTS people (
	Id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FirstName VARCHAR(50) NULL DEFAULT NULL,
	MiddleName VARCHAR(50) NULL DEFAULT NULL,
	LastName VARCHAR(50) NULL DEFAULT NULL,
	Age INT(10) NULL DEFAULT NULL,
	Genre CHAR(9) NULL DEFAULT NULL 
)