CREATE TABLE IF NOT EXISTS users (
	Id INT(10) NOT NULL AUTO_INCREMENT,
	Login VARCHAR(50) UNIQUE NOT NULL DEFAULT '',
	AccesKey VARCHAR(50) NOT NULL DEFAULT '',
	PRIMARY KEY (Id)
) ENGINE=INNODB DEFAULT CHARSET=latin1 COLLATE='latin1_swedish_ci';